[[redirects]]
  from = "/store"
  to = "https://medusa-production-f254.up.railway.app/store"
  status = 200
  force = true
  headers = {X-From = "Netlify"}
[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"