[[redirects]]
  from = "/"
  to = "https://medusa-production-f254.up.railway.app/"
  status = 200
  force = true
  headers = {X-From = "Netlify"}
[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"